const jobData = [
  {
    id: "1",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "WE'RE HIRING IN RUSSIA",
    description: "Looking for a sharp, driven and versatile Individual",
    location: "Moscow, Russia",
    status: "active",
    workingHours: 40,
    salary: 2500,
    currency: "USD",
    facilities: ["Accommodation", "Health Insurance", "Flight Tickets"],
  },
  {
    id: "2",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "URGENTLY REQUIRED For Domino's Pizza Restaurant in KSA",
    description:
      "Pizza Maker, Service Crew, Team Member, Assistant Waiter, Counter Staff",
    location: "Saudi Arabia",
    status: "active",
    workingHours: 48,
    salary: 1200,
    currency: "SAR",
    facilities: ["Free Meals", "Transportation"],
  },
  {
    id: "3",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "WE ARE HIRING! For QCON in Qatar (Oil & Gas Project)",
    description: "Multiple positions available in construction and engineering",
    location: "Qatar",
    status: "active",
    workingHours: 50,
    salary: 3500,
    currency: "QAR",
    facilities: ["Housing Allowance", "Yearly Bonus", "Health Insurance"],
  },
  {
    id: "4",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "URGENT REQUIREMENT For Bader Al Mulla & Bros Co. in Kuwait",
    description:
      "Welding Supervisor, Pipe Fabricator and other technical positions",
    location: "Kuwait",
    status: "active",
    workingHours: 45,
    salary: 500,
    currency: "KWD",
    facilities: ["Overtime Pay", "Annual Leave"],
  },
  {
    id: "5",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "FREE RECRUITMENT POSITIONS",
    description:
      "MIG Welder, Structural Fabricator, Assistant Structural positions available",
    location: "Dubai, UAE",
    status: "active",
    workingHours: 48,
    salary: 1800,
    currency: "AED",
    facilities: ["Visa Sponsorship", "Health Card"],
  },
  {
    id: "6",
    imageUrl: "/placeholder.svg?height=200&width=300",
    title: "POSITIONS Available",
    description:
      "Camp Boss & Catering Supervisor, Trainee Camp Boss, Assistant Cook, South Indian Cook",
    location: "Various Locations",
    status: "active",
    workingHours: 44,
    salary: 1500,
    currency: "USD",
    facilities: ["Food Allowance", "Accommodation"],
  },
];

export default jobData;
